#
## TODO -- why isn't this in source control?
echo "sourcing .bashrc"
#
# Stop OSX from complaining about default shell
export BASH_SILENCE_DEPRECATION_WARNING=1

# export HOME="/Users/mnicosia"

## original line: # scutil --proxy | grep ProxyAutoConfigURLString | grep ".intel.com" > /dev/null
# scutil --proxy | grep ProxyAutoConfigURLString | grep "wpad" > /dev/null
# ret=$?
# if [ $ret -eq 0 ]; then
#   export http_proxy=http://proxy-chain.intel.com:911
#   export https_proxy=http://proxy-chain.intel.com:912
#   export ftp_proxy=http://proxy-chain.intel.com:911
#   export socks_proxy=proxy-chain.intel.com:1080
#   export no_proxy=intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,.local,127.0.0.0/8,172.16.0.0/12,134.134.0.0/16
#   export HTTP_PROXY=http://proxy-chain.intel.com:911
#   export HTTPS_PROXY=http://proxy-chain.intel.com:912
#   export FTP_PROXY=http://proxy-chain.intel.com:911
#   export SOCKS_PROXY=proxy-chain.intel.com:1080
#   export NO_PROXY=intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,.local,127.0.0.0/8,172.16.0.0/12,134.134.0.0/16
# fi

# Proxy configuration according to https://github.com/intel-innersource/applications.infrastructure.caas.caas-demo
export http_proxy=http://proxy-dmz.intel.com:912; export https_proxy=http://proxy-dmz.intel.com:912; export no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,.intel.com,localhost,127.0.0.1

eval "$(/opt/homebrew/bin/brew shellenv)"

PATH+=":$HOME/bin"
PATH+=":/opt/homebrew/opt/mysql-client/bin"
export PATH

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
