echo "Sourcing .bash_profile"

# Path to the bash it configuration
export BASH_IT="/Users/pivotal/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME="${HOME}/dotfiles/pivotal/marco-theme.bash"
SCM_GIT_SHOW_MINIMAL_INFO=true

# Load Bash It
source $BASH_IT/bash_it.sh

export PATH="$HOME/bin:$HOME/go/bin:$PATH"
[ -d /usr/local/sbin ] && export PATH=$PATH:/usr/local/sbin

which -s direnv
if [ 0 -eq $? ]; then eval "$(direnv hook bash)"; fi

[ -f ~/.bash_aliases ] && source ~/.bash_aliases

[ -d /usr/local/opt/chruby ] && source /usr/local/opt/chruby/share/chruby/chruby.sh



export CLOUDSDK_PYTHON=/usr/bin/python
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pivotal/google-cloud-sdk/path.bash.inc' ]; then source '/Users/pivotal/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/pivotal/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/pivotal/google-cloud-sdk/completion.bash.inc'; fi

## Set up aceptance for postgres

PROJECT=data-pcf-db
REGISTRY="gcr.io/${PROJECT}"
